name: python

on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
           python-version: '3.12'

      - uses: actions/checkout@v4

      - name: python code
        run: python hello.py

