name: Hello Github Action

on:
  push:
  workflow_dispatch:
  schedule:
      - cron: '30 1 * * *'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Ibrahim
        run: echo "karthick vijay"

      - uses: actions/checkout@v4
        with:
          java-version: '17'
          distribution: 'temurin'

